"""added columns to appointment table

Revision ID: 4c4c1b940ddb
Revises: 
Create Date: 2023-07-25 17:17:42.594854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4c1b940ddb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors_table')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'doctorstable', ['doctor_id'], ['_id'])
        batch_op.create_foreign_key(None, 'user', ['patient_id'], ['_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('doctor_id')
        batch_op.drop_column('patient_id')

    op.create_table('doctors_table',
    sa.Column('_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=500), nullable=False),
    sa.Column('specs_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['specs_id'], ['specializations._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###
