"""appointment adjustment

Revision ID: 8328c200a7ae
Revises: 
Create Date: 2023-08-15 19:50:12.095175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8328c200a7ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('recommendations')

    # ### end Alembic commands ###
