"""initial migrate

Revision ID: f835d2bb5fae
Revises: 
Create Date: 2023-07-21 22:47:16.319407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f835d2bb5fae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specs_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'specializations', ['specs_id'], ['_id'])
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.VARCHAR(length=500), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('specs_id')

    # ### end Alembic commands ###
